services:
  app:
    build: .
    env_file: .env.production
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks: [botnet]

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: molecula_portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks: [botnet]

  redis:
    image: redis:8.2.1-alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redisdata:/data
    restart: unless-stopped
    networks: [botnet]

networks:
  botnet:

volumes:
  pgdata:
  redisdata:
